kumuluzee:
  name: jdbc-primerjalnik-cen
  version: 1.0.0
  debug: true
  env:
    name: dev
  server:
    base-url: http://localhost:8081
    http:
      port: 8081
  datasources:
    - jndi-name: jdbc/PrimerjalnikCenDB
      connection-url: jdbc:postgresql://localhost:5432/primerjalnik-cen
      username: dbuser
      password: postgres
      pool:
        max-size: 1
  openapi-mp:
    ui:
      server-auto-config:
        enabled: true
        original-uri-check: true
  dev:
    scan-libraries:
      - models
      - lib
      - services
  health:
    checks:
      data-source-health-check:
        jndi-name: jdbc/PrimerjalnikCenDB
        type: liveness
      disk-space-health-check:
        threshold: 100000000
  metrics:
    web-instrumentation:
      - name: kosarice-endpoint
        url-pattern: /v1/kosarice/*
  logs:
    config-file: '<?xml version="1.0" encoding="UTF-8"?>
                           <Configuration name="comments">
                               <Appenders>
                                   <Console name="console" target="SYSTEM_OUT">
                                       <PatternLayout pattern="%d %p %marker %m %X %ex %n"/>
                                   </Console>
                                   <Socket name="logstash" host="625c2d49-19b3-438d-a67d-fc1d7398e073-ls.logit.io"
                                   port="15136" protocol="udp">
                                       <JSONLayout complete="false" compact="true" eventEol="true" charset="UTF-8" properties="true"/>
                                   </Socket>
                               </Appenders>
                               <Loggers>
                                   <!-- Default logger -->
                                   <Root level="all">
                                       <AppenderRef ref="console" level="info" />
                                       <AppenderRef ref="logstash" level="trace" />
                                   </Root>
                               </Loggers>
                           </Configuration>'
config-properties:
  maintenance-mode: false
  broken: false